baseURL: http://davecurry.net
languageCode: en-us
title: davecurry.net
pagerSize: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: G-E1BD6QPGYB

minify:
    disableXML: true
    # minifyOutput: true

taxonomies:
    category: categories
    tag: tags
    series: series

menu:
    main:
        - name: Who Me?
          url: pages/about
          weight: 1

params:
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: false
    favicon: "/favicon.ico"
    comments: false
    # images: ["papermod-cover.png"]

    mainSections:
    - posts

    homeInfoParams:
        Title: >
          Dave Curry
          
          ## Sr. Design Director for [HBO Max/Max](hbomax.jpg) at Warner Bros. Discovery ##
        
        Content: >
          - Previously WarnerMedia, HBO, and #AgencyLife

          -

          - My exceptional team and I consistently strive to evolve and enhance Max's user experience for our global customers. Product design is a never-ending journey of improvement and innovation.

          -

    socialIcons: # optional
        - name: "LinkedIn"
          url: "http://linkedin.com/in/davecurry"

