baseURL: https://davecurry.net
languageCode: en-us
title: davecurry.net
pagerSize: 5
theme: PaperMod

relativeURLs: true
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

service:
    googleAnalytics: 
        ID: G-E1BD6QPGYB

minify:
    disableXML: true
    # minifyOutput: true

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true

menu:
    main:
        - name: Currently Reading
          url: pages/reading
          weight: 1
        - name: Who Me?
          url: pages/about
          weight: 2

params:
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: false
    favicon: "favicons/favicon.ico"
    comments: false
    # images: ["papermod-cover.png"]
    cover:
        hiddenInList: false     # show cover in list/preview views
        hiddenInSingle: true   # show cover on the post page itself

    mainSections:
    - posts

    homeInfoParams:
        Title: "Dave Curry"
        Content: |
          ## Design Leader for [HBO Max](/hbomax.jpg) at Warner Bros. Discovery ##
          
          - 
          
          - Previously WarnerMedia, HBO, and #AgencyLife

          -

          - My exceptional team and I consistently strive to evolve and enhance the HBO Max user experience for our global customers. Product design is a never-ending journey of improvement, experimentation, and innovation.

    socialIcons: # optional
        - name: "LinkedIn"
          url: "http://linkedin.com/in/davecurry"

